# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

version = 1

[[annotations]]
path = [
    "README.md",
]
precedence = "override"
SPDX-License-Identifier = "MPL-2.0"
SPDX-FileCopyrightText = "2025 System76, Inc."
