# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

version = 1

[[annotations]]
path = ["Cargo.lock"]
precedence = "override"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"

[[annotations]]
path = [
    "README.md",
    "docs/**/*.md",
]
precedence = "override"
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "2025 System76, Inc."
