# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

version = 1

[[annotations]]
path = [
    "README.md",
    "res/splash.bmp",
]
precedence = "override"
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "2025 System76, Inc."


[[annotations]]
path = [
    "res/shell.efi",
]
precedence = "override"
SPDX-License-Identifier = "BSD-2-Clause"
SPDX-FileCopyrightText = "2008 Intel Corporation"
