# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

version = 1

[[annotations]]
path = [
    "README.md",
    "res/checkbox_checked.bmp",
    "res/checkbox_unchecked.bmp",
]
precedence = "override"
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "2025 System76, Inc."

[[annotations]]
path = [
    "res/FiraSans-Regular.ttf",
    "res/FiraSans-LICENSE",
]
precedence = "override"
SPDX-License-Identifier = "OFL-1.1-RFN"
SPDX-FileCopyrightText = "2012-2015 The Mozilla Foundation and Telefonica S.A."
